name: ✨ Feature Request
description: Suggest a new feature or improvement for JaaS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make JaaS better? We'd love to hear it! 💡
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area does this feature relate to?
      options:
        - API Endpoints
        - Joke Database
        - Documentation
        - Tooling / Validation
        - GitHub Actions / CI
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples for the feature request.
