name: 🎭 New Joke Submission
description: Submit a new joke to add to the JaaS database
title: "[Joke]: "
labels: ["new-joke"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a joke! 🎉 Please fill out the details below.
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this joke belong to?
      options:
        - programming
        - security
        - general
        - dad
        - pun
        - dark
        - workplace
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Joke Type
      description: Is this a single-line joke or a two-part (setup/delivery) joke?
      options:
        - single
        - twopart
    validations:
      required: true
  - type: textarea
    id: joke
    attributes:
      label: Joke Text
      description: |
        For **single** type: Enter the full joke.
        For **twopart** type: Enter the setup on the first line and the delivery on the second line.
      placeholder: |
        Setup: Why do programmers prefer dark mode?
        Delivery: Because light attracts bugs.
    validations:
      required: true
  - type: dropdown
    id: safe
    attributes:
      label: Safe for Work?
      description: Is this joke appropriate for all audiences?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags for this joke
      placeholder: "e.g., coding, bugs, debugging"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: This joke is original or in the public domain
          required: true
        - label: This joke does not contain hate speech or discriminatory content
          required: true
